### ISSUE TITLE
Dependencies and building documentation need more information

### ISSUE THREAD

**Issue by yamilurbina** [donkeysharp/gocho#4]
I tried to build the application but it's missing some documentation on dependencies, yarn and how to build the app. I found these two dependencies need to be installed before executing  `Makefile`:

```go
go get -u -v github.com/jteeuwen/go-bindata/...
go get -u -v github.com/elazarl/go-bindata-assetfs/...
```

Then yarn needs to run `yarn install` on the `ui` folder:

```bash
cd ui
yarn install
```

And I got stuck when trying to install all dependencies recursively using `go get -t -v ./...`. I get the following error:

```bash
# github.com/donkeysharp/gocho/assets
../../donkeysharp/gocho/assets/assets.go:8:33: undefined: Asset
../../donkeysharp/gocho/assets/assets.go:8:50: undefined: AssetDir
../../donkeysharp/gocho/assets/assets.go:8:71: undefined: AssetInfo
```

I think it has to do with executing `go-bindata`, but some help on this part is greatly appreciated.

**Comment by donkeysharp** [comment]
Hey @yamilurbina, 

I added [building docs](https://github.com/donkeysharp/gocho/blob/master/docs/building.md). If you think there are missing steps or have problems on the building process, please let me know.

Regarding dependencies, I used a similar approach as [Kubernetes](https://github.com/kubernetes/kubernetes/tree/master/vendor) on versioning dependencies in the `vendor` directory. Vendor directory was introduced with [Go 1.6][1]. If you need to add a new dependecy I'm using [govendor](https://github.com/kardianos/govendor) tool for that.

For your problem with go-bindata, it's due to the `make generate` command that was not executed (it's in the docs).

[1]: (https://golang.org/doc/go1.6)

**Comment by yamilurbina** [comment]
Thanks, the explanation was pretty good and the building document is now clear. I'm closing this issue.
